site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ‚åÅ

pages:
- What is it?:
    - 'Index': 'index.md'
    - 'Overview': 'nightscout/overview.md'
- Install: 'nightscout/new_user.md'
- Update:
    - 'Updating your site': 'update/update.md'
    - 'Migrating to Atlas': 'update/migrate_heroku.md'
    - 'Migrating from Azure': 'update/migrate_azure.md'
- Configure:
    - 'Configure your Nightscout': 'nightscout/setup_variables.md'
    - 'Uploaders': 'nightscout/uploaders.md'
    - 'Close the loop': 'nightscout/close_loop.md'
- Use:
    - 'Reports': 'nightscout/reports.md'
    - 'IF This Then That': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
- Troubleshoot:
    - 'Troubleshooting': 'nightscout/troublehoot.md'
    - 'Nightscout stopped working': 'nightscout/mlab_cleanup.md'
