site_name: Nightscout
theme: flatly
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ‚åÅ

pages:
- Home: 'index.md'
- Nightscout:
    - 'Overview': 'nightscout/overview.md'
    - 'Brand New NS': 'nightscout/new_user.md'
    - 'Retrofit Existing NS': 'nightscout/update_user.md'
    - 'Setup Troubleshooting': 'nightscout/troublehoot.md'
    - 'NS Stopped Working': 'nightscout/mlab_cleanup.md'
    - 'Remote Overrides': 'nightscout/remote-overrides.md'
    - 'IFTTT': 'nightscout/ifttt.md'
    - 'Pebble': 'nightscout/pebble.md'
    - 'Remote Notifications': 'nightscout/pushover.md'
    - 'Reports': 'nightscout/reports.md'
- Update:
    - 'Updating your site': 'update/update.md'
